### ISSUE TITLE
Template crashes on Startup

### ISSUE THREAD

**Issue by Crashdummyy** [xamarin/MobileBlazorBindings#120]
The App won't even start on my phone.

<details><summary>StackTrace</summary>

```sh
time: 1592768925149
msg: android.runtime.JavaProxyThrowable: System.TypeLoadException: Could not resolve type with token 01000037 from typeref (expected class 'System.IAsyncDisposable' in assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51')
  at Microsoft.Extensions.Hosting.HostBuilder.Build () [0x00032] in <d9111cb5801c4daa9c9326e1803d1ae3>:0 
  at GameBuddy.App..ctor () [0x00031] in <0225221e4b36483893c6e95e77ac79ec>:0 
  at GameBuddy.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0002f] in <1b97f57bef474e3db30a715fe3f4e6ce>:0 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00012] in <1c532ee08245465d92c8f3cd1e8ff034>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.8(intptr,intptr,intptr)
stacktrace: android.runtime.JavaProxyThrowable: System.TypeLoadException: Could not resolve type with token 01000037 from typeref (expected class 'System.IAsyncDisposable' in assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51')
  at Microsoft.Extensions.Hosting.HostBuilder.Build () [0x00032] in <d9111cb5801c4daa9c9326e1803d1ae3>:0 
  at GameBuddy.App..ctor () [0x00031] in <0225221e4b36483893c6e95e77ac79ec>:0 
  at GameBuddy.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0002f] in <1b97f57bef474e3db30a715fe3f4e6ce>:0 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00012] in <1c532ee08245465d92c8f3cd1e8ff034>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.8(intptr,intptr,intptr)
	at md58d8dc41c6931572c5d53fe48f6caca1d.MainActivity.n_onCreate(Native Method)
	at md58d8dc41c6931572c5d53fe48f6caca1d.MainActivity.onCreate(MainActivity.java:30)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)
```

</details>

```sh
$ dotnet new -i Microsoft.MobileBlazorBindings.Templates::0.3.26-preview

$ dotnet new mobileblazorbindings -o GameBuddy
```

**Comment by Eilon** [comment]
Hi @Crashdummyy sorry you're running into this problem. Did you make any other changes, or is it just the default template? Also, did you deploy to a physical phone device, or is it in the emulator? Can you provide info on which phone you're using or which emulated phone you're using?

I haven't seen this error before, but I found an answer from a Xamarin.Forms team member on StackOverflow: https://stackoverflow.com/questions/41163887/could-not-resolve-type-with-token-0100000f

Perhaps that might offer some hints?

**Comment by Crashdummyy** [comment]
Hi @Eilon thanks for the quick reply.
I was just about to close this issue right this moment :rofl: 

<img width=200 height=400 src="https://user-images.githubusercontent.com/15139403/85237766-93875480-b429-11ea-9c3b-35a04a4e550b.jpg">

I tryed a lot of things and finally resolved my problems by changing my java version
( Oracle JDK 11.0.4 --> OpenJDK 11.0.4 ).  
Maybe just plain reinstalling helped at all.

Sorry for the inconvenience

**Comment by Eilon** [comment]
Hmm that's odd, but perhaps that is what fixed it. Thank you for reporting this. It will help keep an eye out in case another person sees this same issue. I'm glad you got it working!
